import { useEffect, useRef, useState } from 'react';
import './image-studio.css';
const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';
type Operation = 'generate' | 'edit' | 'enhance';
const MAX_BYTES = 10 * 1024 * 1024;
export default function ImageStudio() {
 const [operation,setOperation]=useState<Operation>('generate'); const [prompt,setPrompt]=useState(''); const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState<string|null>(null); const [result,setResult]=useState<string|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null); const inputRef=useRef<HTMLInputElement>(null);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 const chooseFile=(selected?:File)=>{if(!selected)return;if(!['image/png','image/jpeg','image/webp'].includes(selected.type)){setError('Please select a PNG, JPG or WebP image.');return;}if(selected.size>MAX_BYTES){setError('Image must be 10 MB or smaller.');return;}setFile(selected);setPreview(URL.createObjectURL(selected));setResult(null);setError(null);};
 const submit=async()=>{if(operation!=='generate'&&!file){setError('Upload an image first.');return;}if(!prompt.trim()&&operation!=='enhance'){setError('Describe what you want to create or change.');return;}setLoading(true);setError(null);setResult(null);try{const image=file?{mimeType:file.type,data:(await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)}))}:undefined;const r=await fetch(`${API_URL}/api/images`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({operation,prompt:prompt.trim(),image})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error?.message||data.error||'Image generation failed.');setResult(data.imageDataUrl);}catch(e){setError(e instanceof Error?e.message:'Image generation failed.');}finally{setLoading(false);}};
 return <section className="image-studio"><header><p className="eyebrow">SUNVIX AI</p><h1>Image Studio</h1><p>Create, edit and enhance images with AI.</p></header><div className="image-tabs" role="tablist">{(['generate','edit','enhance'] as Operation[]).map(item=><button key={item} type="button" className={operation===item?'active':''} onClick={()=>{setOperation(item);setError(null)}} role="tab" aria-selected={operation===item}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div><div className="image-studio-grid"><div className="image-panel">{operation!=='generate'&&<button className="image-dropzone" type="button" onClick={()=>inputRef.current?.click()}><input ref={inputRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>chooseFile(e.target.files?.[0])}/>{preview?<img src={preview} alt="Selected source"/>:<><span>＋</span><strong>Upload an image</strong><small>PNG, JPG or WebP · up to 10 MB</small></>}</button>}<label htmlFor="image-prompt">Prompt</label><textarea id="image-prompt" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={operation==='enhance'?'Optional: describe the enhancement...':'Describe the image you want...'} rows={5}/><button className="image-generate-button" type="button" disabled={loading} onClick={()=>void submit()}>{loading?'Generating…':operation==='generate'?'Generate image':operation==='edit'?'Edit image':'Enhance image'}</button>{error&&<p className="image-error" role="alert">{error}</p>}</div><div className="image-result-panel">{result?<img src={result} alt="AI generated result"/>:<div className="image-empty"><span>✦</span><p>Your result will appear here</p><small>Fast AI image generation and editing</small></div>}</div></div></section>;
}
