import { ApiError } from '../types/chat';
export interface ConversationSummary { id: string; title: string | null; createdAt: string; updatedAt: string }
interface ConversationsResponse { conversations: ConversationSummary[] }
interface MessagesResponse { messages: Array<{ id: string; role: 'user' | 'assistant'; content: string }> }
export type ChatGenerationMode = 'new' | 'retry' | 'regenerate'; export type ChatProvider = 'gemini' | 'openrouter';
export interface ChatSource { chunkId: string; documentId: string; documentName: string; page?: number | null; section?: string | null; score: number }
export interface ChatRagOptions { enabled?: boolean; documentId?: string; knowledgeBaseId?: string }
export type ChatStreamEvent = { event: 'token'; data: { token: string } } | { event: 'sources'; data: { sources: ChatSource[] } } | { event: 'done'; data: { conversationId: string; ttftMs: number | null; latencyMs: number } } | { event: 'error'; data: { code: string; message: string } };
export class ChatRequestError extends Error { constructor(public readonly status: number, public readonly code: string, message: string) { super(message); this.name = 'ChatRequestError'; } }
const API_URL = import.meta.env.PROD ? '' : import.meta.env.VITE_API_URL;
function messageForStatus(status: number): string { switch (status) { case 400:return 'Invalid chat request. Please check the selected AI model.'; case 401:return 'Your session has expired. Please sign in again.'; case 403:return 'You do not have permission to use this conversation.'; case 429:return 'You are sending messages too quickly. Please wait and try again.'; case 502:case 503:return 'The AI service is temporarily unavailable. Please try again.'; case 500:return 'Something went wrong on the server. Please try again.'; default:return 'Unable to send your message. Please try again.'; } }
async function request<T>(path: string): Promise<T> { const response = await fetch(`${API_URL}${path}`, { credentials: 'include' }); if (!response.ok) { const errorData = await response.json().catch(() => null) as { error?: ApiError } | null; throw new ChatRequestError(response.status, errorData?.error?.code ?? 'REQUEST_FAILED', messageForStatus(response.status)); } return response.json() as Promise<T>; }
export async function getConversations() { return request<ConversationsResponse>('/api/conversations'); }
export async function getConversationMessages(conversationId: string) { const result = await request<MessagesResponse>(`/api/conversations/${conversationId}/messages`); return { ...result, messages: [...result.messages].reverse() }; }
export async function streamMessage(message: string, conversationId: string | undefined, onEvent: (event: ChatStreamEvent) => void, signal: AbortSignal, mode: ChatGenerationMode = 'new', provider: ChatProvider = 'gemini', rag?: ChatRagOptions): Promise<void> {
  const storedDocumentId = typeof window !== 'undefined' ? window.localStorage.getItem('ai-chatbot:rag-document') || undefined : undefined; const storedKnowledgeBaseId = typeof window !== 'undefined' ? window.localStorage.getItem('ai-chatbot:rag-kb') || undefined : undefined; const scope = rag || (storedDocumentId ? { enabled: true, documentId: storedDocumentId } : storedKnowledgeBaseId ? { enabled: true, knowledgeBaseId: storedKnowledgeBaseId } : undefined); let response: Response;
  try { response = await fetch(`${API_URL}/api/chat`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json', Accept: 'text/event-stream' }, body: JSON.stringify({ message, ...(conversationId ? { conversationId } : {}), mode, provider, ...(scope?.enabled || scope?.documentId || scope?.knowledgeBaseId ? { rag: scope, documentId: scope?.documentId, knowledgeBaseId: scope?.knowledgeBaseId } : {}) }), signal }); } catch (error) { if (error instanceof DOMException && error.name === 'AbortError') throw error; throw new ChatRequestError(0, 'NETWORK_ERROR', 'Network connection failed. Check your connection and try again.'); }
  if (!response.ok) { const errorData = await response.json().catch(() => null) as { error?: ApiError } | null; throw new ChatRequestError(response.status, errorData?.error?.code ?? 'REQUEST_FAILED', messageForStatus(response.status)); }
  if (!response.body) throw new ChatRequestError(0, 'STREAM_UNAVAILABLE', 'Streaming is unavailable. Please try again.');
  const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = '';
  const consume = (raw: string) => { buffer += raw; const events = buffer.split('\n\n'); buffer = events.pop() ?? ''; for (const block of events) { const eventLine = block.split('\n').find((line) => line.startsWith('event: ')); const dataLine = block.split('\n').find((line) => line.startsWith('data: ')); if (!eventLine || !dataLine) continue; const event = eventLine.slice(7) as ChatStreamEvent['event']; const data = JSON.parse(dataLine.slice(6)); onEvent({ event, data } as ChatStreamEvent); } };
  try { while (true) { const { done, value } = await reader.read(); if (done) break; consume(decoder.decode(value, { stream: true })); } consume(decoder.decode()); if (signal.aborted) throw new DOMException('Generation aborted', 'AbortError'); } finally { try { await reader.cancel(); } catch {} reader.releaseLock(); }
}
